name: "Testing"
description: "Testing out github actions"
author: "lemillermicrosoft"
branding:
  icon: "alert-circle"
  color: "red"

inputs:
  repo-token:
    description: "Token for the repo. Can be passed in using {{ secrets.GITHUB_TOKEN }}"
    required: true

runs:
  using: "docker"
  image: "dockerfile"
