name: Add PR Description

on: pull_request

permissions:
  pull-requests: read

jobs:
  message:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Repo
        uses: actions/checkout@v3.5.2

      - uses: ./
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
        env: # Set Azure credentials secret as an input
          AZURE_OPENAI_DEPLOYMENT_NAME: ${{ vars.AZURE_OPENAI_DEPLOYMENT_NAME }}
          AZURE_OPENAI_API_ENDPOINT: ${{ vars.AZURE_OPENAI_API_ENDPOINT }}
          AZURE_OPENAI_API_KEY: ${{ secrets.AZURE_OPENAI_API_KEY }}
          AZURE_OPENAI_DEPLOYMENT_LABEL: ${{ vars.AZURE_OPENAI_DEPLOYMENT_LABEL }}
